version: "3"
services:
  salto_code:
    build:
      context: ./salto_code
      dockerfile: Dockerfile
    image: salto_code
    ports:
      - "3001:3000"
    networks:
      - strapi
    volumes:
      - "./salto_code:/app"
  
  salto_atoms:
    build:
      context: ./salto_atoms
      dockerfile: Dockerfile
    image: salto_atoms
    ports:
      - "3000:3000"
    networks:
      - strapi
    volumes:
      - "./salto_atoms:/app"
  
  #jenkins:
    #build: ./jenkins
    #ports:
     # - "8081:8080"
      #- "50000:50000"
    #user: root  # Jenkinsをrootユーザーとして実行
    #volumes:
     # - jenkins_home:/var/jenkins_home
     # - /var/run/docker.sock:/var/run/docker.sock
    #networks:
     # - strapi

volumes:
  jenkins_home:
  
networks:
  strapi:
