version: "3"
services:
  salto_atoms:
    build:
      context: ./salto_atoms
      dockerfile: Dockerfile.prod
      args:
        NODE_ENV: production
    environment:
      NODE_ENV: production
    volumes:
      - ./salto_atoms:/app
    networks:
      - strapi

  # nginx:
  #   build: 
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./nginx/log:/var/log/nginx
  #     - ./nginx/letsencrypt:/etc/letsencrypt
  #     - ./salto_atoms/build:/usr/share/nginx/html
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   networks:
  #     - strapi

  strapi:
    container_name: strapi
    build:
      context: ./strapi
      dockerfile: Dockerfile.prod
    image: strapi:latest
    restart: unless-stopped
    environment:
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}

      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DATABASE_HOST: strapiDB
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production 
    volumes:
      - ./strapi/src:/opt/app/src
      - ./strapi/package.json:/opt/package.json
      - ./strapi/package-lock.json:/opt/package-lock.json
      - .env.production:/opt/app/.env.production
      - ./strapi/public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - strapi
    depends_on:
      - strapiDB
      
  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 
    restart: unless-stopped
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - strapi-data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - strapi
      
volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
