version: "3"
services:
  # salto_code:
  #   build:
  #     context: ./salto_code
  #     dockerfile: Dockerfile
  #   image: salto_code
  #   ports:
  #     - "3001:3000"
  #   networks:
  #     - strapi
  #   volumes:
  #     - "./salto_code:/app"
  
  salto_atoms:
    build:
     context: ./salto_atoms
     dockerfile: Dockerfile
     image: salto_atoms
     ports:
       - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - webnet
    volumes:
      - "./salto_atoms:/app"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80" # 本番環境でのポート設定
    volumes:
      - ./nginx:/etc/nginx/conf.d # Nginxの設定ファイルをコンテナにマウント
      - ./salto_atoms/build:/usr/share/nginx/html # salto_atomsのビルドされたファイルをNginxのドキュメントルートにマウント
    depends_on:
      - salto_atoms
    networks:
      - webnet # 修正: ネットワーク名を統一

networks:
  webnet: {}
  
  

