version: "3"
services:
  salto_code:
    build:
      context: ./salto_code
      dockerfile: Dockerfile
    image: salto_code
    ports:
      - "3001:3000"
    networks:
      - strapi
    volumes:
      - "./salto_code:/app"
  
  salto_atoms:
    build:
      context: ./salto_atoms
      dockerfile: Dockerfile
    image: salto_atoms
    ports:
      - "3000:3000"
    networks:
      - strapi
    volumes:
      - "./salto_atoms:/app"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - salto_atoms
      - salto_code
    networks:
      - strapi
  
jenkins:
    image: jenkins/jenkins:lts-jdk11
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - strapi

volumes:
  jenkins_home:
  
networks:
  strapi:
