
version: '3.8'
services:
  nginx:
    build: 
      context: ./dockerfiles/nginx
      dockerfile: Dockerfile
    container_name: nginx-container
    volumes:
      - ../../src:/var/www
      - PHP-FPM-SOCK:/var/run/php-fpm
      - $NGINX_DEFAULT_CONF_PATH:/etc/nginx/conf.d/default.conf
      - $NGINX_CONF_PATH:/etc/nginx/nginx.conf
      - $NGINX_LOG_PATH:$SYS_NGINX_LOG_PATH
    environment:
      TZ: $TIME_ZONE
      LANG: $LANG
    ports:
      - "80:80"
      #- "443:443"   
    depends_on:
      - laravel
    networks:
      - container-link  

  laravel:
    build:
      context: ../../  
      dockerfile: infra/docker/dockerfiles/php-fpm/Dockerfile
    container_name: laravel-container
    volumes:
      - ../../src:/var/www  
      - PHP-FPM-SOCK:/var/run/php-fpm
      - $PHP_INI_PATH/php.ini:$SYS_PHP_CONF_PATH/php/php.ini:delegated
      - $PHP_FPM_CONF_PATH/php-fpm.conf:$SYS_PHP_CONF_PATH/php-fpm.conf:delegated
      - $PHP_FPM_CONFD_PATH/www.conf:$SYS_PHP_CONF_PATH/php-fpm.d/www.conf:delegated
      - $PHP_FPM_CONFD_PATH/zzz-docker.conf:$SYS_PHP_CONF_PATH/php-fpm.d/zzz-docker.conf:delegated
    environment:
      TZ: $TIME_ZONE
      LANG: $LANG 
    expose:
      - '9000'
    entrypoint: "/bin/sh -c 'chmod -R o+w /var/www && docker-php-entrypoint php-fpm'"
    networks:
      - container-link
   
  mysql:
    build:
      context: ./dockerfiles/mysql
      dockerfile: Dockerfile
    container_name: mysql-container
    networks:
      - container-link
    volumes:
      - $MYSQL_CONF_PATH/my.cnf:$SYS_ROOT_PATH/my.cnf:delegated
      - $MYSQL_LOG_PATH:$SYS_MYSQL_LOG_PATH:delegated
      - $DB_INIT_PATH:/docker-entrypoint-initdb.d/:delegated
      - MYSQL-DATA:/var/lib/mysql:cached
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $ENV_MYSQL_ROOT_PASSWORD
      MYSQL_USER: $ENV_MYSQL_USER
      MYSQL_PASSWORD: $ENV_MYSQL_PASSWORD
      TZ: $TIME_ZONE
      LANG: $LANG

  jenkins:
    container_name: jenkins-container
    image: jenkins/jenkins:lts
    ports:
      - "8888:8080"
    volumes:
      - $JENKINS_HOME:$SYS_JENKINS_PATH
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: $TIME_ZONE
      LANG: $LANG

  adminer:
    container_name: adminer-container
    image: adminer
    restart: unless-stopped
    ports:
      - '9090:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    networks:
      - container-link

volumes:
  PHP-FPM-SOCK:
  MYSQL-DATA:
  JENKINS-DATA:
networks:
  container-link:  
    name: mynetwork.internal
    driver: bridge


