const ProblemsData = [
    {
      language: ["Html", "Css", "JavaScript"],
      category: "新卒研修",
      problem_description: "フロントエンド初級講座",
      problem_count: 10,
      status: "受講済",
      like_count: 3,
      name: "Saltoくん",
      avatar: "/test.png",
      parameter: "3rC70BJiCJsX",
    },
    {
      language: ["MySql"],
      category: "新卒研修",
      problem_description: "MySql初級講座",
      problem_count: 10,
      status: "未受講",
      like_count: 3,
      name: "Saltoくん",
      avatar: "/test.png",
      parameter: "NDn4EaQP57el",
    },
    // {
    //   language: ["MySql"],
    //   category: "新卒研修",
    //   problem_description: "SELECT文中級講座",
    //   problem_count: 10,
    //   status: "未受講",
    //   like_count: 3,
    //   name: "Saltoくん",
    //   avatar: "/test.png",
    //   parameter: "GlTdAuG5DvJ8",
    // },
    // {
    //   language: ["Html", "Css"],
    //   category: "新卒研修",
    //   problem_description: "Flex初級講座",
    //   problem_count: 10,
    //   status: "受講中",
    //   like_count: 3,
    //   name: "Saltoくん",
    //   avatar: "/test.png",
    //   parameter: "R9cp1BrNO1s0",
    // },
    // {
    //   language: ["Html", "JavaScript"],
    //   category: "新卒研修",
    //   problem_description: "JavaScript初級講座",
    //   problem_count: 10,
    //   status: "未受講",
    //   like_count: 3,
    //   name: "Saltoくん",
    //   avatar: "/test.png",
    //   parameter: "RlDpL8M6ZFCz",
    // },
    // {
    //   language: ["MySql"],
    //   category: "新卒研修",
    //   problem_description: "Mysql練習問題1",
    //   problem_count: 10,
    //   status: "未受講",
    //   like_count: 3,
    //   name: "Saltoくん",
    //   avatar: "/test.png",
    //   parameter: "gVvprtlRJFEZ",
    // },
  ];

  export default ProblemsData;