export const categoryData = {
    "categories": [
      {
        "category": "資格",
        "subcategories": [
          {
            "rank": "S",
            "skills": [
              "ITストラテジスト試験（ST）",
              "システム監査技術者試験（AU）",
              "Oracle Master Platinum"
            ]
          },
          {
            "rank": "A",
            "skills": [
              "プロジェクトマネージャ試験（PM）",
              "システムアーキテクト試験（SA）",
              "IT サービスマネージャ試験（SM）",
              "ネットワークスペシャリスト試験（NW）",
              "情報処理安全確保支援士試験（SC）",
              "AWS Certified Solutions Architect - Professional（SAP-C02）",
              "AWS Certified DevOps Engineer - Professional（DOP-C02）",
              "AWS Certified Advanced Networking - Specialty（ANS-C01）",
              "AWS Certified Database - Specialty（DBS-C01）",
              "AWS Certified Security – Specialty（SCS-C02）",
              "Azure Solutions Architect Expert(AZ-305)",
              "Oracle Master Gold",
              "Oracle認定Javaプログラマ Gold",
              "Javaプログラミング能力認定試験 1級",
              "PMP"
            ]
          },
          {
            "rank": "B",
            "skills": [
              "データベーススペシャリスト試験（DB）",
              "応用情報技術者試験（AP）",
              "AWS Certified Solutions Architect - Associate (SAA-C03)",
              "AWS Certified SysOps Administrator – Associate（SOA-C02）",
              "AWS Certified Developer - Associate（DVA-C02）",
              "Azure Developer Associate(AZ-204)",
              "Azure Administrator Associate(AZ-104)",
              "Azure Database Administrator Associate(DP-300)",
              "Azure Data Engineer Associate(DP-203)",
              "Azure Data Scientist Associate(DP-100)",
              "Azure Security Engineer Associate(AZ-500)",
              "Data Engineer",
              "Cloud DevOps Engineer",
              "Cloud Security Engineer",
              "Cloud Network Engineer",
              "Machine Learning Engineer",
              "Oracle Cloud Infrastructure 2022 Architect Professional(1Z0-997-22-JPN)",
              "Oracle Cloud Infrastructure 2022 Cloud Operations Professional(1Z0-1067-22-JPN)",
              "Oracle Cloud Infrastructure 2022 Developer Professional(1Z0-1084-22-JPN)",
              "Oracle Cloud Infrastructure 2022 Security Professional(1Z0-1104-22-JPN)",
              "Oracle Cloud Infrastructure DevOps Professional(1Z0-1109-22-JPN)",
              "Oracle Cloud Infrastructure Data Science 2022 Professional(1Z0-1110-22-JPN)",
              "Oracle Cloud Infrastructure 2022 Observability and Management Professional(1Z0-1111-22-JPN)",
              "Javaプログラミング能力認定試験 2級",
              "Android技術者認定試験 プロフェッショナル",
              "PHP8技術者認定上級/準上級試験",
              "LinuCレベル3",
              "CCAr(Cisco Certified Architect)",
              "CISSP"
            ]
          },
          {
            "rank": "C",
            "skills": [
              "エンベデッドシステムスペシャリスト試験（ES）",
              "基本情報技術者試験（FE）",
              "Cloud Architect",
              "Cloud Database Engineer",
              "Cloud Developer",
              "OSS-DB Gold",
              "Oracle認定Javaプログラマ Silver",
              "PHP8技術者認定初級試験",
              "LinuCレベル2",
              "認定Kubernetes管理者 (CKA-JP)",
              "認定Kubernetesセキュリティスペシャリスト（CKS-JP）",
              "Python 3 エンジニア認定実践試験",
              "CCNP(Cisco Certified Network Professional)",
              "CCIE(Cisco Certified Internet Expert)",
              "CCDE(Cisco Certified Design Expert)",
              "情報処理技術者能力認定試験(1級)"
            ]
          },
          {
            "rank": "D",
            "skills": [
              "情報セキュリティマネジメント試験（SG）",
              "ITパスポート（IP）",
              "AWS Certified Cloud Practitioner（CLF-C01）",
              "Azure Fundamentals(AZ-900)",
              "Azure Data Fundamentals(DP-900)",
              "Cloud Digital Leader",
              "Cloud Engineer",
              "Google Workspace Administrator",
              "Oracle Cloud Infrastructure 2022 Architect Associate(1Z0-1072-22-JPN)",
              "Oracle Cloud Infrastructure 2022 Foundations Associate(1Z0-1085-22-JPN)",
              "Oracle Master Bronze",
              "Oracle Master Silver",
              "OSS-DB Silver",
              "Oracle認定Javaプログラマ Bronze",
              "Javaプログラミング能力認定試験 3級",
              "Android技術者認定試験 ベーシック",
              "LinuCレベル1",
              "HTML5プロフェッショナル認定試験 レベル1",
              "HTML5プロフェッショナル認定試験 レベル2",
              "認定Kubernetesクラウドネイティブアソシエイト（KCNA-JP）",
              "認定Kubernetesアプリケーション開発者（CKAD-JP）",
              "Python 3 エンジニア認定データ分析試験",
              "Python 3 エンジニア認定基礎試験",
              "Web検定 Webリテラシー",
              "Web検定 Webデザイン",
              "Web検定 Webディレクション",
              "Web検定 Webプロデュース",
              "色彩検定(R) 1級",
              "色彩検定(R) 2級",
              "色彩検定(R) 3級",
              "色彩検定(R) UC級",
              "カラーコーディネーター検定試験 アドバンス",
              "カラーコーディネーター検定試験 スタンダード",
              "カラーデザイン検定 1級",
              "カラーデザイン検定 2級",
              "カラーデザイン検定 3級",
              "Illustrator クリエイター能力認定試験 エキスパート",
              "Illustrator クリエイター能力認定試験 スタンダード",
              "Photoshop クリエイター能力認定試験 エキスパート",
              "Photoshop クリエイター能力認定試験 スタンダード",
              "ウェブデザイン検定 1級",
              "ウェブデザイン検定 2級",
              "ウェブデザイン検定 3級",
              "Webクリエイター能力認定試験 エキスパート",
              "Webクリエイター能力認定試験 スタンダード",
              "CCT(Cisco Certified Technician)",
              "CCNA(Cisco Certified Network Associate)",
              "ウェブ解析士",
              "上級ウェブ解析士",
              "ウェブ解析士マスター",
              "情報処理技術者能力認定試験(2級)",
            "情報処理技術者能力認定試験(3級)",
          ]
        }
      ]
    }
  ]
}